require 'cocoapods-deploy/dependency'
require 'cocoapods-deploy/deploy_lockfile'
require 'cocoapods-deploy/deploy_podfile'
require 'cocoapods-deploy/deploy_analyzer'
require 'cocoapods-deploy/deploy_installer'
require 'cocoapods-deploy/command'
